### ISSUE TITLE
Fix styles for Read more section in product page

### ISSUE THREAD

**Issue by gauthamksn** [hlxsites/fonterra-fernleaf#134]
Column block style breaking for lesser screens

- https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products/milk-powder-for-whole-family
- https://www.fernleaf.com.my/en/products/milk-powder-for-whole-family.html

Tablet view:
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/1e5dbcf5-f5c5-4885-b191-e7ec6cfb7b7b)
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/bec9c866-8ae1-41aa-a4b4-cf4ae673b14e)

Mobile view:
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/3340507b-7a74-485f-8eb3-fe8716116f7e)
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/71a31322-06de-47d6-93ae-5737d15d2dad)

**Comment by sselvara** [comment]
1. we follow stacking approach for mobile and Tablet view, 
ie,
desktop => horizontal columns
tablet/mobile => vertical columns

Hence,  in tablet image will not be made overlapped with first column as per the current site.

2. Is fixed along with button sizing.

**Comment by mkbansal1** [comment]
@sselvara Layouts are still broken on column block in main branch (seems like your changes got reverted)
<img width="855" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/f94cc167-c9e9-4c28-9b30-e9be955f156d">
<img width="870" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/49dde724-ecb4-4c99-86e1-539210ff15a1">
<img width="989" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/ebe24ffc-e0d4-4dc2-8113-5ad93840655d">
<img width="630" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/a43d99d5-a0d6-43f7-a22a-b3a46e6f67f8">

**Comment by sselvara** [comment]
Need to fix mobile view of product category columns. https://104-hero-banner-fix--fonterra-fernleaf--hlxsites.hlx.page/en/products/calciyum
